/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/M51lgyEisu5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function ApproveTab() {
  return (
    <Tabs className="w-[400px]" defaultValue="add">
      <TabsList className="grid w-full grid-cols-3">
        <TabsTrigger value="add">Add</TabsTrigger>
        <TabsTrigger value="remove">Remove</TabsTrigger>
        <TabsTrigger value="update">Update</TabsTrigger>
      </TabsList>
      <TabsContent value="add">
        <Card>
          <CardHeader>
            <CardTitle>Add</CardTitle>
            <CardDescription>Add a new item here.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2" />
          <CardFooter>
            <Button>Save</Button>
          </CardFooter>
        </Card>
      </TabsContent>
      <TabsContent value="remove">
        <Card>
          <CardHeader>
            <CardTitle>Remove</CardTitle>
            <CardDescription>Remove an existing item here.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2" />
          <CardFooter>
            <Button>Delete</Button>
          </CardFooter>
        </Card>
      </TabsContent>
      <TabsContent value="update">
        <Card>
          <CardHeader>
            <CardTitle>Update</CardTitle>
            <CardDescription>Update an existing item here.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2" />
          <CardFooter>
            <Button>Save</Button>
          </CardFooter>
        </Card>
      </TabsContent>
    </Tabs>
  )
}
