/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gIgOp0qgOJb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function DepartmentDetails() {
  return (
    <div className="grid md:grid-cols-2 gap-8 items-start">
      <div className="flex items-start gap-4 text-center md:gap-8">
        <img
          alt="Faculty"
          className="rounded-full"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200"
        />
        <div className="grid gap-1 text-left">
          <div className="font-semibold text-2xl">Dr. Alice Johnson</div>
          <div className="font-semibold">Professor</div>
          <div className="text-sm">Computer Science</div>
          <Link className="font-semibold underline" href="#">
            Contact
          </Link>
        </div>
      </div>
      <div className="flex items-start gap-4 text-center md:gap-8">
        <img
          alt="Faculty"
          className="rounded-full"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200"
        />
        <div className="grid gap-1 text-left">
          <div className="font-semibold text-2xl">Dr. Mark Lee</div>
          <div className="font-semibold">Associate Professor</div>
          <div className="text-sm">Mechanical Engineering</div>
          <Link className="font-semibold underline" href="#">
            Contact
          </Link>
        </div>
      </div>
      <div className="flex items-start gap-4 text-center md:gap-8">
        <img
          alt="Faculty"
          className="rounded-full"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200"
        />
        <div className="grid gap-1 text-left">
          <div className="font-semibold text-2xl">Dr. Sarah Clark</div>
          <div className="font-semibold">Assistant Professor</div>
          <div className="text-sm">Biology</div>
          <Link className="font-semibold underline" href="#">
            Contact
          </Link>
        </div>
      </div>
      <div className="flex items-start gap-4 text-center md:gap-8">
        <img
          alt="Faculty"
          className="rounded-full"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200"
        />
        <div className="grid gap-1 text-left">
          <div className="font-semibold text-2xl">Dr. Alex Turner</div>
          <div className="font-semibold">Professor</div>
          <div className="text-sm">Chemistry</div>
          <Link className="font-semibold underline" href="#">
            Contact
          </Link>
        </div>
      </div>
    </div>
  )
}
